// 사용자 관련 액션 타입
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

// 코스 관련 액션 타입
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

// 이벤트 관련 액션 타입
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

// 피드백 관련 액션 타입
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS';
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS';

// 포럼 및 포스트 관련 액션 타입
export const CREATE_FORUM_SUCCESS = 'CREATE_FORUM_SUCCESS';
export const FETCH_FORUMS_SUCCESS = 'FETCH_FORUMS_SUCCESS';
export const ADD_POST_TO_FORUM_SUCCESS = 'ADD_POST_TO_FORUM_SUCCESS';
export const FETCH_POSTS_IN_FORUM_SUCCESS = 'FETCH_POSTS_IN_FORUM_SUCCESS';

// 알림 관련 액션 타입
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const FETCH_USER_NOTIFICATIONS_SUCCESS = 'FETCH_USER_NOTIFICATIONS_SUCCESS';
export const MARK_NOTIFICATION_AS_READ_SUCCESS = 'MARK_NOTIFICATION_AS_READ_SUCCESS';

// 추가적인 액션 타입은 필요에 따라 여기에 정의할 수 있습니다.
